# Generated by Django 5.1.3 on 2024-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorecurrente',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagounico',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
