# Generated by Django 5.1.3 on 2024-12-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pagounico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagorecurrente',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Importante - Urgente'), (2, 'Importante - No Urgente'), (3, 'No Importante - Urgente'), (4, 'No Importante - No Urgente')]),
        ),
        migrations.AlterField(
            model_name='pagounico',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Importante - Urgente'), (2, 'Importante - No Urgente'), (3, 'No Importante - Urgente'), (4, 'No Importante - No Urgente')]),
        ),
    ]
